# .NET Desktop

# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- Beta
- librarysplit

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'ME3Explorer.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'WinRelease'

steps:
# Change artifact name when the version major/minor changes
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $artifactname = "me3explorernightly_4.2.0.$(Build.BuildId)"
      # Date--------------------------------------------
      $date=$(Get-Date -Format s);
      Write-Host "##vso[task.setvariable variable=time]$date"
      # Commit Message (Multiliner)-----------------------
      $commitMessageFull = git log -1 --pretty=%B
      $numlines = $($commitMessageFull | measure).Count
      if ($numlines > 0) { 
        $commitMessageFull=[system.String]::Join(" ", $commitMessageFull)
      }
      Write-Host "##vso[task.setvariable variable=commitMessageFull]$commitMessageFull"
      # Author-------------------------------------------
      $author = git log -1 --pretty=format:'%an'
      Write-Host "##vso[task.setvariable variable=author]$author"
      Write-Host "Author: $($author)"
      # API Keys and versioning--------------------------
      $apikeysprivatefile = "namespace ME3Explorer`n{`n    public static partial class APIKeys`n    {`n        public static string Private_AppCenter {get;} = `"$(AppCenterKey)`";`n    }`n}"
      Set-Content -Path "$(Build.Repository.LocalPath)\ME3Explorer\APIKeysPrivate.cs" -Value $apikeysprivatefile
      (Get-Content .\ME3Explorer\Properties\AssemblyInfo.cs).replace("0`"","$(Build.BuildId)`"") | out-file -FilePath .\ME3Explorer\Properties\AssemblyInfo.cs
      # Get report generator
      dotnet tool install -g dotnet-reportgenerator-globaltool

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Test ME3ExplorerCore
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'ME3ExplorerCore.Tests/ME3ExplorerCore.Tests.csproj'
    arguments: '--configuration WinAzureRelease /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:DebugType=pdbonly -v normal'
    publishTestResults: true

# Find output file
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      reportgenerator -reports:**/coverage.cobertura.xml -targetdir:CoverateReport -reporttypes:"HtmlInline_AzurePipelines;Cobertura" -classfilters:"-*Gammtek*"

# - task: reportgenerator@4
#   inputs:
#     reports: '**/cobertura.coverage.xml'
#     targetdir: 'CoverageReport'
#     title: 'ME3ExplorerCore Code Coverage Report'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '**/coverage.cobertura.xml'
    reportDirectory: 'CoverageReport'
    failIfCoverageEmpty: true

# Build ME3Explorer UI Application
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/ME3Explorer/bin/x64/$(buildConfiguration)'
    includeRootFolder: false
    archiveType: '7z'
    archiveFile: '$(Build.ArtifactStagingDirectory)/me3explorer_nightly_cibuild_4.2.0.$(Build.BuildId).7z'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'me3explorernightly_4.2.0.$(Build.BuildId)'
    publishLocation: 'Container'

# Notify ME3Tweaks that a new beta build has been built
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Webrequest using powershell since invokerestapi doesn't work on anything but server jobs
      Invoke-WebRequest -Uri $(me3explorerApiEndpoint)
    errorActionPreference: 'continue'

- task: ado-discord-webhook@1
  inputs:
    channelId: '$(discord_channel_id)'
    webhookKey: '$(discord_webhook_key)'
    name: 'Azure DevOps CI'
    avatar: 'https://i.imgur.com/mUtPj2S.png'
    messageType: 'embeds'
    embeds: |
      [{
        "title": "ME3Explorer - ME3Tweaks Fork Build Complete",
        "description": "A new nightly build of ME3Explorer has been built. Click this link, then expand the dropdown and download the 7z file. Nightly builds may be unstable and have bugs.",
        "thumbnail": {
          "url": "https://i.imgur.com/mUtPj2S.png",
          "height": 64,
          "width": 64
        },
        "fields": [{
          "name": "Triggering commit",
          "value": "$(commitMessageFull)"
        },
        {
          "name": "Author",
          "value": "$(author)"
        },
        {
          "name": "Branch",
          "value": "$(Build.SourceBranchName)"
        },
        {
          "name": "Version",
          "value": "4.2.0.$(Build.BuildId)"
        }],
        "url": "https://dev.azure.com/ME3Tweaks/ME3Explorer/_build/results?buildId=$(Build.BuildId)&view=artifacts",
        "timestamp": "$(time)"
      }]